/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    domains: [
      'res.cloudinary.com',
      'localhost',
      'images.unsplash.com',
      'plus.unsplash.com',
      'images.pexels.com',
      'img.freepik.com',
      'media.istockphoto.com',
      'www.shutterstock.com',
      'www.dreamstime.com',
      'www.123rf.com',
      'www.alamy.com',
      'www.gettyimages.com',
      'www.depositphotos.com',
      'www.bigstockphoto.com',
      'www.stock.adobe.com',
      'www.canva.com',
      'www.pixabay.com',
      'www.rawpixel.com',
      'www.vecteezy.com',
      'www.flaticon.com',
      'www.freepik.com',
      'www.icons8.com',
      'www.iconfinder.com',
      'www.iconmonstr.com',
      'www.icon54.com',
      'www.icon-icons.com',
      'www.iconarchive.com',
      'www.iconfont.cn',
      'www.iconfinder.com',
      'www.iconmonstr.com',
      'www.icon54.com',
      'www.icon-icons.com',
      'www.iconarchive.com',
      'www.iconfont.cn',
      'www.iconfinder.com',
      'www.iconmonstr.com',
      'www.icon54.com',
      'www.icon-icons.com',
      'www.iconarchive.com',
      'www.iconfont.cn',
    ],
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '**',
      },
    ],
  },
};

module.exports = nextConfig;